DATA("张鹤伦-劳动号子.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-劳动号子.m4a","1");
DATA("张鹤伦-十分美好.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-十分美好.m4a","2");
DATA("张鹤伦-女儿情.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-女儿情.m4a","3");
DATA("张鹤伦-妹妹若是来看我.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-妹妹若是来看我.m4a","4");
DATA("张鹤伦-学小曲 (2).m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-学小曲 (2).m4a","5");
DATA("张鹤伦-学小曲.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-学小曲.m4a","6");
DATA("张鹤伦-德云老司机张鹤伦专场.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-德云老司机张鹤伦专场.m4a","7");
DATA("张鹤伦-快乐节奏.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-快乐节奏.m4a","8");
DATA("张鹤伦-我为歌狂.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-我为歌狂.m4a","9");
DATA("张鹤伦-我是歌手.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-我是歌手.m4a","10");
DATA("张鹤伦-最天使.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-最天使.m4a","11");
DATA("张鹤伦-最炫天团.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-最炫天团.m4a","12");
DATA("张鹤伦-歌曲 因为爱情.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-歌曲 因为爱情.m4a","13");
DATA("张鹤伦-歌曲梦西游.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-歌曲梦西游.m4a","14");
DATA("张鹤伦-流金岁月.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-流金岁月.m4a","15");
DATA("张鹤伦-海阔天空.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-海阔天空.m4a","16");
DATA("张鹤伦-滴答 燃烧的翅膀 北京北京.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-滴答 燃烧的翅膀 北京北京.m4a","17");
DATA("张鹤伦-相思赋予谁.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-相思赋予谁.m4a","18");
DATA("张鹤伦-那些年的歌.m4a","http://cloud.2345.ltd/OnedriveCN/德云社/张鹤伦/张鹤伦-那些年的歌.m4a","19");