DATA("azu-angel.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/azu-angel.mp3","1");
DATA("juju-この夜を止めてよ.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/juju-この夜を止めてよ.mp3","2");
DATA("rania-DrFeelGood.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/rania-DrFeelGood.mp3","3");
DATA("中岛美嘉-雪華.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/中岛美嘉-雪華.mp3","4");
DATA("中島みゆき-容易受伤的女人原曲.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/中島みゆき-容易受伤的女人原曲.mp3","5");
DATA("初音未来-甩葱歌.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/初音未来-甩葱歌.mp3","6");
DATA("大冢爱-プラネタリウム.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/大冢爱-プラネタリウム.mp3","7");
DATA("大冢爱-桃ノ花ビラ.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/大冢爱-桃ノ花ビラ.mp3","8");
DATA("宇多田光-First_Love.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/宇多田光-First_Love.mp3","9");
DATA("宗次郎-故乡的原风景.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/宗次郎-故乡的原风景.mp3","10");
DATA("少女时代-mr taxi.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/少女时代-mr taxi.mp3","11");
DATA("少女时代-the boys.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/少女时代-the boys.mp3","12");
DATA("川嶋あい-大丈夫だよ.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/川嶋あい-大丈夫だよ.mp3","13");
DATA("日本歌曲 星の在り処.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/日本歌曲 星の在り処.mp3","14");
DATA("日本歌曲-漠然の莹.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/日本歌曲-漠然の莹.mp3","15");
DATA("滨崎步-A_Song_For_Xx.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/滨崎步-A_Song_For_Xx.mp3","16");
DATA("滨崎步-Blue_Bird.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/滨崎步-Blue_Bird.mp3","17");
DATA("滨崎步-depend_on_you.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/滨崎步-depend_on_you.mp3","18");
DATA("滨崎步-fly_high.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/滨崎步-fly_high.mp3","19");
DATA("滨崎步-M.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/滨崎步-M.mp3","20");
DATA("滨崎步-To_Be.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/滨崎步-To_Be.mp3","21");
DATA("谷村新司-いい日旅立ち.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/谷村新司-いい日旅立ち.mp3","22");
DATA("谷村新司-カノン.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/谷村新司-カノン.mp3","23");
DATA("谷村新司-君の歌.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/谷村新司-君の歌.mp3","24");
DATA("谷村新司-忘れないで.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/谷村新司-忘れないで.mp3","25");
DATA("谷村新司-昂一すばゐ.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/谷村新司-昂一すばゐ.mp3","26");
DATA("谷村新司-星.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/谷村新司-星.mp3","27");
DATA("谷村新司-睡莲.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/谷村新司-睡莲.mp3","28");
DATA("谷村新司-风姿花传.mp3","http://cloud.2345.ltd/OnedriveCN/音乐视听/日本音乐/谷村新司-风姿花传.mp3","29");