DATA("MeghnaMishra-NachdiPhira","https://vercel.11.wf/free163person/音乐视听/印度音乐/MeghnaMishra-NachdiPhira.mp3","1");
DATA("印度歌曲-KaruneshPunjab","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度歌曲-KaruneshPunjab.mp3","2");
DATA("印度音乐-WadaNaTod","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-WadaNaTod.mp3","3");
DATA("印度音乐-一首超爽的印度舞曲","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-一首超爽的印度舞曲.mp3","4");
DATA("印度音乐-不要不要","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-不要不要.mp3","5");
DATA("印度音乐-印度之花","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-印度之花.mp3","6");
DATA("印度音乐-印度音乐","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-印度音乐.mp3","7");
DATA("印度音乐-印度魔咒_dj舞曲","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-印度魔咒_dj舞曲.mp3","8");
DATA("印度音乐-吉特巴舞曲踩着我的节拍跳起来吧","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-吉特巴舞曲踩着我的节拍跳起来吧.mp3","9");
DATA("印度音乐-吉米来吧","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-吉米来吧.mp3","10");
DATA("印度音乐-大悲咒","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-大悲咒.mp3","11");
DATA("印度音乐-天使之吻 亲嘴歌","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-天使之吻 亲嘴歌.mp3","12");
DATA("印度音乐-天使之吻_亲嘴歌_女声版","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-天使之吻_亲嘴歌_女声版.mp3","13");
DATA("印度音乐-天竺少女","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-天竺少女.mp3","14");
DATA("印度音乐-奴里 清楚版","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-奴里 清楚版.mp3","15");
DATA("印度音乐-妩媚撩人_巨好听的印度慢摇舞曲","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-妩媚撩人_巨好听的印度慢摇舞曲.mp3","16");
DATA("印度音乐-情字路上","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-情字路上.mp3","17");
DATA("印度音乐-想要对你说爱你的人","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-想要对你说爱你的人.mp3","18");
DATA("印度音乐-慢摇_非常舒服的节奏","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-慢摇_非常舒服的节奏.mp3","19");
DATA("印度音乐-慢摇精华舞曲_酒吧dj音乐","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-慢摇精华舞曲_酒吧dj音乐.mp3","20");
DATA("印度音乐-慢摇英文跳舞曲","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-慢摇英文跳舞曲.mp3","21");
DATA("印度音乐-我终生爱你至死不渝","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-我终生爱你至死不渝.mp3","22");
DATA("印度音乐-热辣媚娘_恰恰","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-热辣媚娘_恰恰.mp3","23");
DATA("印度音乐-用爱对我","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-用爱对我.mp3","24");
DATA("印度音乐-的士高劲歌舞曲","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-的士高劲歌舞曲.mp3","25");
DATA("印度音乐-神秘国度_印度民族音乐","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-神秘国度_印度民族音乐.mp3","26");
DATA("印度音乐-秘密桑巴","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-秘密桑巴.mp3","27");
DATA("印度音乐-纯净如天簌的","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-纯净如天簌的.mp3","28");
DATA("印度音乐-绝对动听的印度歌曲","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-绝对动听的印度歌曲.mp3","29");
DATA("印度音乐-肚皮舞 卡西卡少女之春","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-肚皮舞 卡西卡少女之春.mp3","30");
DATA("印度音乐-芭杜尔快来吧","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-芭杜尔快来吧.mp3","31");
DATA("印度音乐-迷幻音乐","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-迷幻音乐.mp3","32");
DATA("印度音乐-阿育王 忧伤的笛子","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-阿育王 忧伤的笛子.mp3","33");
DATA("印度音乐-雷鬼","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-雷鬼.mp3","34");
DATA("印度音乐-音乐心情_一首超好听的印度歌曲","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-音乐心情_一首超好听的印度歌曲.mp3","35");
DATA("印度音乐-风情舞动","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-风情舞动.mp3","36");
DATA("印度音乐-麻吉_印度神游","https://vercel.11.wf/free163person/音乐视听/印度音乐/印度音乐-麻吉_印度神游.mp3","37");
DATA("阿育王主题曲-RoshiniSe","https://vercel.11.wf/free163person/音乐视听/印度音乐/阿育王主题曲-RoshiniSe.mp3","38");
DATA("阿育王插曲-AsokaTheme","https://vercel.11.wf/free163person/音乐视听/印度音乐/阿育王插曲-AsokaTheme.mp3","39");