DATA("Adaro-Es Ist Ein Schnee Gefallen.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Adaro-Es Ist Ein Schnee Gefallen.mp3","1");
DATA("Adele-Hello.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Adele-Hello.mp3","2");
DATA("Adele-Rolling in the Deep.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Adele-Rolling in the Deep.mp3","3");
DATA("Air Supply-Making Love Out Of Nothing At All.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Air Supply-Making Love Out Of Nothing At All.mp3","4");
DATA("Alan Walker-Alone.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Alan Walker-Alone.mp3","5");
DATA("Alan Walker-Faded.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Alan Walker-Faded.mp3","6");
DATA("Alan Walker-The Spectre.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Alan Walker-The Spectre.mp3","7");
DATA("AmyDiamond-Heartbeats.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/AmyDiamond-Heartbeats.mp3","8");
DATA("Ann Winsborn-La La Love On My Mind.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Ann Winsborn-La La Love On My Mind.mp3","9");
DATA("Aqua-My Oh My.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Aqua-My Oh My.mp3","10");
DATA("Ava Max-Salt.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Ava Max-Salt.mp3","11");
DATA("Ava Max-Sweet but Psycho.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Ava Max-Sweet but Psycho.mp3","12");
DATA("AvrilLavigne-IamWithYou.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/AvrilLavigne-IamWithYou.mp3","13");
DATA("Backstreet Boys-As Long As You Love Me.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Backstreet Boys-As Long As You Love Me.mp3","14");
DATA("Backstreet Boys-Everybody.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Backstreet Boys-Everybody.mp3","15");
DATA("Backstreet Boys-I want it that way.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Backstreet Boys-I want it that way.mp3","16");
DATA("Backstreet Boys-Larger Than Life.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Backstreet Boys-Larger Than Life.mp3","17");
DATA("Bertie Higgins-Casablanca.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Bertie Higgins-Casablanca.mp3","18");
DATA("Blue-All Rise.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Blue-All Rise.mp3","19");
DATA("Blue-One Love.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Blue-One Love.mp3","20");
DATA("Bon Jovi-Its My Life.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Bon Jovi-Its My Life.mp3","21");
DATA("BwO-Sunshine In The Rain.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/BwO-Sunshine In The Rain.mp3","22");
DATA("CaraDillon-Craigie Hill.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/CaraDillon-Craigie Hill.mp3","23");
DATA("Carpenters-Yesterday Once More.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Carpenters-Yesterday Once More.mp3","24");
DATA("Celine Dion-All By Myself.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Celine Dion-All By Myself.mp3","25");
DATA("Celine Dion-Because You Loved Me.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Celine Dion-Because You Loved Me.mp3","26");
DATA("Celine Dion-I Surrender.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Celine Dion-I Surrender.mp3","27");
DATA("Celine Dion-My Heart Will Go On.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Celine Dion-My Heart Will Go On.mp3","28");
DATA("Celine Dion-The Power Of Love.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Celine Dion-The Power Of Love.mp3","29");
DATA("Charlie Puth、Selena Gomez-We Dont Talk Anymore.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Charlie Puth、Selena Gomez-We Dont Talk Anymore.mp3","30");
DATA("CHROMANCE-Wrap Me In Plastic.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/CHROMANCE-Wrap Me In Plastic.mp3","31");
DATA("Coldplay-Yellow.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Coldplay-Yellow.mp3","32");
DATA("Dan Fogelberg-Sutters Mill.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Dan Fogelberg-Sutters Mill.mp3","33");
DATA("Dana Winner-Moonlight Shadow.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Dana Winner-Moonlight Shadow.mp3","34");
DATA("Daniel Powter-Free Loop.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Daniel Powter-Free Loop.mp3","35");
DATA("Darin-Be What You Wanna Be.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Darin-Be What You Wanna Be.mp3","36");
DATA("Delacey-Dream It Possible.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Delacey-Dream It Possible.mp3","37");
DATA("DemiLovato-LetItGo.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/DemiLovato-LetItGo.mp3","38");
DATA("Djokawari-luv letter.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Djokawari-luv letter.mp3","39");
DATA("Eagles-Hotel California.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Eagles-Hotel California.mp3","40");
DATA("EdSheeran-Shape Of You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/EdSheeran-Shape Of You.mp3","41");
DATA("Emilia-big big world.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Emilia-big big world.mp3","42");
DATA("Eminem、Rihanna-Love The Way You Lie.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Eminem、Rihanna-Love The Way You Lie.mp3","43");
DATA("Enya-May It Be.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Enya-May It Be.mp3","44");
DATA("Enya-Only Time.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Enya-Only Time.mp3","45");
DATA("Era-The Mass.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Era-The Mass.mp3","46");
DATA("Gabriel MarianI-ts My Life.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Gabriel MarianI-ts My Life.mp3","47");
DATA("Gareth Gates-Anyone of Us.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Gareth Gates-Anyone of Us.mp3","48");
DATA("George Benson-Nothings Gonna Change My Love For You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/George Benson-Nothings Gonna Change My Love For You.mp3","49");
DATA("George Michael-Careless Whisper.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/George Michael-Careless Whisper.mp3","50");
DATA("Grant Miller-Colder Than Ice.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Grant Miller-Colder Than Ice.mp3","51");
DATA("Groove Coverage-Far Away From Home.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Groove Coverage-Far Away From Home.mp3","52");
DATA("Groove Coverage-God Is a Girl.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Groove Coverage-God Is a Girl.mp3","53");
DATA("Groove Coverage-She.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Groove Coverage-She.mp3","54");
DATA("Hawk Nelson、Jonathan Steingard-Sold Out.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Hawk Nelson、Jonathan Steingard-Sold Out.mp3","55");
DATA("HayleyWestenra-never say goodbye.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/HayleyWestenra-never say goodbye.mp3","56");
DATA("Hedy West-500 Miles.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Hedy West-500 Miles.mp3","57");
DATA("Ina Wroldsen-I Wanted You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Ina Wroldsen-I Wanted You.mp3","58");
DATA("James Blunt-Youre Beautiful.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/James Blunt-Youre Beautiful.mp3","59");
DATA("Jennifer Rush-The Power of Love.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Jennifer Rush-The Power of Love.mp3","60");
DATA("Jewel-Stand.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Jewel-Stand.mp3","61");
DATA("Joan Jett-I Hate Myself For Loving You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Joan Jett-I Hate Myself For Loving You.mp3","62");
DATA("John Denver-Take Me Home, Country Roads.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/John Denver-Take Me Home, Country Roads.mp3","63");
DATA("Justin Bieber、Luis Fonsi、Daddy Yankee-Despacito.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Justin Bieber、Luis Fonsi、Daddy Yankee-Despacito.mp3","64");
DATA("Justin Bieber-Baby.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Justin Bieber-Baby.mp3","65");
DATA("Kaoma-Lambada.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Kaoma-Lambada.mp3","66");
DATA("Katy Perry-Roar.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Katy Perry-Roar.mp3","67");
DATA("Kelly Clarkson-Because of You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Kelly Clarkson-Because of You.mp3","68");
DATA("Kelly Clarkson-Catch My Breath.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Kelly Clarkson-Catch My Breath.mp3","69");
DATA("Kelly Clarkson-Stronger.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Kelly Clarkson-Stronger.mp3","70");
DATA("Kim Taylor-I Am You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Kim Taylor-I Am You.mp3","71");
DATA("Klymaxx-I Miss You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Klymaxx-I Miss You.mp3","72");
DATA("Ladygaga-Poker Face.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Ladygaga-Poker Face.mp3","73");
DATA("Lenka-The Show.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Lenka-The Show.mp3","74");
DATA("Lenka-Trouble Is a Friend.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Lenka-Trouble Is a Friend.mp3","75");
DATA("Leo Sayer-More Than I Can Say.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Leo Sayer-More Than I Can Say.mp3","76");
DATA("Linkin Park-Numb.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Linkin Park-Numb.mp3","77");
DATA("LionelRichie-SayYouSayMe.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/LionelRichie-SayYouSayMe.mp3","78");
DATA("Lovestoned-Bye Bye Bye.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Lovestoned-Bye Bye Bye.mp3","79");
DATA("Luis Fonsi-Despacito.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Luis Fonsi-Despacito.mp3","80");
DATA("M2M-Pretty Boy.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/M2M-Pretty Boy.mp3","81");
DATA("M2M-The Day You Went Away.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/M2M-The Day You Went Away.mp3","82");
DATA("Madonna-Papa Dont Preach.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Madonna-Papa Dont Preach.mp3","83");
DATA("MariaArredondo-Burning.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/MariaArredondo-Burning.mp3","84");
DATA("Maroon 5-Sugar.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Maroon 5-Sugar.mp3","85");
DATA("Matthew Lien-Bressanone.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Matthew Lien-Bressanone.mp3","86");
DATA("Maxwell-Its Ok.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Maxwell-Its Ok.mp3","87");
DATA("Meg Myers-Running Up That Hill.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Meg Myers-Running Up That Hill.mp3","88");
DATA("Michael Jackson-Beat It.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Michael Jackson-Beat It.mp3","89");
DATA("Michael Jackson-Billie Jean.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Michael Jackson-Billie Jean.mp3","90");
DATA("Michael Jackson-Dangerous.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Michael Jackson-Dangerous.mp3","91");
DATA("Michael Jackson-HealTheWorld.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Michael Jackson-HealTheWorld.mp3","92");
DATA("Michael Jackson-You Are Not Alone.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Michael Jackson-You Are Not Alone.mp3","93");
DATA("Michael Learns To Rock-Take Me To Your Heart.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Michael Learns To Rock-Take Me To Your Heart.mp3","94");
DATA("MinnieRiperton-LovingYou.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/MinnieRiperton-LovingYou.mp3","95");
DATA("Modern Talking-Brother Louie.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Modern Talking-Brother Louie.mp3","96");
DATA("Nana-lonely.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Nana-lonely.mp3","97");
DATA("Nu Virgos-StopStopStop.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Nu Virgos-StopStopStop.mp3","98");
DATA("Olly Murs-That Girl.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Olly Murs-That Girl.mp3","99");
DATA("O-Zone-Dragostea din tei.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/O-Zone-Dragostea din tei.mp3","100");
DATA("P!nk-Try.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/P!nk-Try.mp3","101");
DATA("Queen-We Will Rock You.flac","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Queen-We Will Rock You.flac","102");
DATA("R. Kelly-I Believe I Can Fly.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/R. Kelly-I Believe I Can Fly.mp3","103");
DATA("Rachel Platten-Lone Ranger.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Rachel Platten-Lone Ranger.mp3","104");
DATA("Richard Marx-Right Here Waiting.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Richard Marx-Right Here Waiting.mp3","105");
DATA("Ricky Martin-生命之杯.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Ricky Martin-生命之杯.mp3","106");
DATA("Robbie Williams-Better Man.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Robbie Williams-Better Man.mp3","107");
DATA("Sarah Brightman、Andrea Bocelli-Time To Say Goodbye.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Sarah Brightman、Andrea Bocelli-Time To Say Goodbye.mp3","108");
DATA("Sarah Brightman-Scarborough Fair.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Sarah Brightman-Scarborough Fair.mp3","109");
DATA("Sarah Coonor-just one last dance.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Sarah Coonor-just one last dance.mp3","110");
DATA("SarahCoonor-From Sarah With Love.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/SarahCoonor-From Sarah With Love.mp3","111");
DATA("Sasha Alex Sloan-Dancing With Your Ghost.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Sasha Alex Sloan-Dancing With Your Ghost.mp3","112");
DATA("Savage Garden-Truly Madly Deeply.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Savage Garden-Truly Madly Deeply.mp3","113");
DATA("Secret Garden-Nocturne.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Secret Garden-Nocturne.mp3","114");
DATA("Selena Gomez-Wolves.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Selena Gomez-Wolves.mp3","115");
DATA("Shakin Stevens-Because I Love You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Shakin Stevens-Because I Love You.mp3","116");
DATA("Shayne Ward-Unchained Melody.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Shayne Ward-Unchained Melody.mp3","117");
DATA("Sia-Cheap Thrills.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Sia-Cheap Thrills.mp3","118");
DATA("Sia-Move Your Body.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Sia-Move Your Body.mp3","119");
DATA("Sia-Unstoppable.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Sia-Unstoppable.mp3","120");
DATA("Simon And Garfunkel-The Sound of Silence.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Simon And Garfunkel-The Sound of Silence.mp3","121");
DATA("Smile.DK-Butterfly.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Smile.DK-Butterfly.mp3","122");
DATA("Starship-Nothings Gonna Stop Us Now.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Starship-Nothings Gonna Stop Us Now.mp3","123");
DATA("Stevie Wonder-I Just Called To Say I Love You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Stevie Wonder-I Just Called To Say I Love You.mp3","124");
DATA("Sweetbox-Dont Push Me.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Sweetbox-Dont Push Me.mp3","125");
DATA("Tatu-30 Minutes.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Tatu-30 Minutes.mp3","126");
DATA("Tatu-Loves Me Not.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Tatu-Loves Me Not.mp3","127");
DATA("Taylor Swift-Love Story.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Taylor Swift-Love Story.mp3","128");
DATA("The Cascades-Rhythm Of The Rain.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/The Cascades-Rhythm Of The Rain.mp3","129");
DATA("The Nolans-Sexy Music.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/The Nolans-Sexy Music.mp3","130");
DATA("The Police-Every Breath You Take.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/The Police-Every Breath You Take.mp3","131");
DATA("Timbaland-Apologize.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Timbaland-Apologize.mp3","132");
DATA("Trademark-Only Love.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Trademark-Only Love.mp3","133");
DATA("Tragedie-Hey Oh.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Tragedie-Hey Oh.mp3","134");
DATA("U2-With Or Without You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/U2-With Or Without You.mp3","135");
DATA("Usher、Lil Jon、Ludacris-Yeah.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Usher、Lil Jon、Ludacris-Yeah.mp3","136");
DATA("Various Artists、Deutschland Sucht Den Superstar-Cry On My Shoulder.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Various Artists、Deutschland Sucht Den Superstar-Cry On My Shoulder.mp3","137");
DATA("Vicetone、Meron Ryan-Walk Thru Fire.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Vicetone、Meron Ryan-Walk Thru Fire.mp3","138");
DATA("Vitas-歌剧2.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Vitas-歌剧2.mp3","139");
DATA("Vitas-星星.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Vitas-星星.mp3","140");
DATA("Westlife-My Love.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Westlife-My Love.mp3","141");
DATA("Westlife-Nothings Going to Change My Love For You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Westlife-Nothings Going to Change My Love For You.mp3","142");
DATA("Westlife-Seasons in the Sun.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Westlife-Seasons in the Sun.mp3","143");
DATA("Whitney Houston-I Have Nothing.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Whitney Houston-I Have Nothing.mp3","144");
DATA("Whitney Houston-I will Always Love You.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/Whitney Houston-I will Always Love You.mp3","145");
DATA("WizKhalifa-See You Again.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/WizKhalifa-See You Again.mp3","146");
DATA("布兰妮-BabyOneMoreTime.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/布兰妮-BabyOneMoreTime.mp3","147");
DATA("布兰妮-everytime.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/布兰妮-everytime.mp3","148");
DATA("卡洛儿-假如爱有天意.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/卡洛儿-假如爱有天意.mp3","149");
DATA("卡洛儿-写给海洋.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/卡洛儿-写给海洋.mp3","150");
DATA("欧美群星-WeAreTheWorld.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/欧美群星-WeAreTheWorld.mp3","151");
DATA("手嶌葵-the rose.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/手嶌葵-the rose.mp3","152");
DATA("斯维特拉娜 斯维吉科娃-天使消逝的地方.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/斯维特拉娜 斯维吉科娃-天使消逝的地方.mp3","153");
DATA("伊莲娜罗尔-我的名字叫伊莲.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/伊莲娜罗尔-我的名字叫伊莲.mp3","154");
DATA("有里知花-I Cry.mp3","https://vercel.11.wf/free163person/音乐视听/欧美音乐/有里知花-I Cry.mp3","155");
